### ISSUE TITLE
ROS-bag KITTI example

### ISSUE THREAD

**Issue by anastasiia-kornilova** [Mitchell-Lee-93/kitti-A-LOAM#1]
Hi! Thanks a lot for such useful repo! Could you share, please, a link to one of the already combined ros-bag files for KITTI?

**Comment by Mitchell-Lee-93** [comment]
I'm sorry that I don't have the link since the size of rosbag files for KITTI is too large (about 80GB).

**Comment by hahakid** [comment]
@anastasiia-kornilova 链接：https://pan.baidu.com/s/1YuvCRdcELh6JvaaqkoFRzQ 
提取码：jkpl  a single subseq of 04 can be download here (the shortest one). And you can generated a bag with the kittle_helper

**Comment by anastasiia-kornilova** [comment]
Thank you, @hahakid @Mitchell-Lee-93! The issue was not to download the whole data archive and to check on some sequence :)
Wish you good luck with your research!
