### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by cristianrubioa** [Mitchell-Lee-93/kitti-A-LOAM#3]
What are the characteristics of your machine to obtain your results?
![Screen Shot 2021-02-19 at 8 26 02 AM](https://user-images.githubusercontent.com/44789319/108510107-1cda7980-728c-11eb-8d6d-b59b25b55df3.png)

I have something like this
Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GH
cpu cores : 2

![Screen Shot 2021-02-19 at 8 28 35 AM](https://user-images.githubusercontent.com/44789319/108510403-780c6c00-728c-11eb-9f26-7bbbce0aa28a.png)

**Comment by cristianrubioa** [comment]
According to: https://github.com/Mitchell-Lee-93/kitti-A-LOAM/issues/2 
Downloading the odometry dataset the result improves.
![Screen Shot 2021-03-17 at 3 04 56 AM](https://user-images.githubusercontent.com/44789319/111434450-8f911600-86cd-11eb-8f72-f382f27e22d5.png)

Although the original LOAM is designed for raw point cloud data rather than processed data such as KITTI data sets.

**Comment by Grandzxw** [comment]
Do you know why the result improve?
